# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ventanaModificarProductoCampos.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialogvmpc(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 558)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 741, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.campoPrecioCompra = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.campoPrecioCompra.setMinimumSize(QtCore.QSize(250, 0))
        self.campoPrecioCompra.setMaximumSize(QtCore.QSize(270, 16777215))
        self.campoPrecioCompra.setObjectName("campoPrecioCompra")
        self.gridLayout.addWidget(self.campoPrecioCompra, 2, 1, 1, 1)
        self.botonCancelar = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.botonCancelar.setMinimumSize(QtCore.QSize(270, 40))
        self.botonCancelar.setMaximumSize(QtCore.QSize(270, 16777215))
        self.botonCancelar.setObjectName("botonCancelar")
        self.gridLayout.addWidget(self.botonCancelar, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.campoNombre = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.campoNombre.setMinimumSize(QtCore.QSize(250, 0))
        self.campoNombre.setMaximumSize(QtCore.QSize(270, 16777215))
        self.campoNombre.setObjectName("campoNombre")
        self.gridLayout.addWidget(self.campoNombre, 0, 1, 1, 1)
        self.campoPrecioVenta = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.campoPrecioVenta.setMinimumSize(QtCore.QSize(250, 0))
        self.campoPrecioVenta.setMaximumSize(QtCore.QSize(270, 16777215))
        self.campoPrecioVenta.setObjectName("campoPrecioVenta")
        self.gridLayout.addWidget(self.campoPrecioVenta, 1, 1, 1, 1)
        self.okBoton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.okBoton.setMinimumSize(QtCore.QSize(270, 40))
        self.okBoton.setMaximumSize(QtCore.QSize(270, 300))
        self.okBoton.setObjectName("okBoton")
        self.gridLayout.addWidget(self.okBoton, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(250, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalFrame = QtWidgets.QFrame(self.gridLayoutWidget)
        self.horizontalFrame.setMaximumSize(QtCore.QSize(16777215, 20))
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButtonSi = QtWidgets.QRadioButton(self.horizontalFrame)
        self.radioButtonSi.setEnabled(True)
        self.radioButtonSi.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButtonSi.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButtonSi.setObjectName("radioButtonSi")
        self.horizontalLayout_2.addWidget(self.radioButtonSi)
        self.radioButtonNo = QtWidgets.QRadioButton(self.horizontalFrame)
        self.radioButtonNo.setMinimumSize(QtCore.QSize(0, 20))
        self.radioButtonNo.setMaximumSize(QtCore.QSize(16777215, 20))
        self.radioButtonNo.setObjectName("radioButtonNo")
        self.horizontalLayout_2.addWidget(self.radioButtonNo)
        self.gridLayout.addWidget(self.horizontalFrame, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Modificar Producto"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Nombre</span></p></body></html>"))
        self.botonCancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Precio Venta</span></p></body></html>"))
        self.okBoton.setText(_translate("Dialog", "Confirmar"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">Precio Compra</span></p></body></html>"))
        self.radioButtonSi.setText(_translate("Dialog", "Sí"))
        self.radioButtonNo.setText(_translate("Dialog", "No"))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">IVA</span></p></body></html>"))
